apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: picalc-git
  params:
    - name: pathToYamlFile
      value: "kubernetes/picalc.yaml"
    - name: imageUrl
      value: <REGISTRY>/default/picalc
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account